export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const GET_PRODUCT_SKU_SUCCESS = "GET_PRODUCT_SKU_SUCCESS";
export const GET_PRODUCT_SKU_FAILURE = "GET_PRODUCT_SKU_FAILURE";

export const GET_SEARCH_PRODUCTS_SUCCESS = 'GET_SEARCH_PRODUCTS_SUCCESS';
export const GET_SEARCH_PRODUCTS_FAILURE = 'GET_SEARCH_PRODUCTS_FAILURE';

export const GET_SEARCH_PRODUCTS_FROM_CART_SUCCESS = 'GET_SEARCH_PRODUCTS_FROM_CART_SUCCESS';
export const GET_SEARCH_PRODUCTS_FROM_CART_FAILURE = 'GET_SEARCH_PRODUCTS_FROM_CART_FAILURE';

export const GET_PRODUCT_ATTRIBUTE_OPTIONS_SUCCESS = 'GET_PRODUCT_ATTRIBUTE_OPTIONS_SUCCESS';
export const GET_PRODUCT_ATTRIBUTE_OPTIONS_FAILURE = 'GET_PRODUCT_ATTRIBUTE_OPTIONS_FAILURE';

export const LOADING = 'LOADING';
export const LOADING_COMPLETE = 'LOADING_COMPLETE';

export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";

export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAILURE = "GET_CART_FAILURE";

export const GET_ATTRIBUTE_SUCCESS = "GET_ATTRIBUTE_SUCCESS";
export const GET_ATTRIBUTE_FAILURE = "GET_ATTRIBUTE_FAILURE";

export const UPDATE_TO_CART_SUCCESS = "UPDATE_TO_CART_SUCCESS";
export const UPDATE_TO_CART_FAILURE = "UPDATE_TO_CART_FAILURE";

export const DELETE_TO_CART_SUCCESS = "DELETE_TO_CART_SUCCESS";
export const DELETE_TO_CART_FAILURE = "DELETE_TO_CART_FAILURE";

export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

export const TOKEN_GENERATION_SUCCESS = "TOKEN_GENERATION_SUCCESS";
export const TOKEN_GENERATION_FAILURE = "TOKEN_GENERATION_FAILURE";

export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
export const GET_CUSTOMERS_FAILURE = "GET_CUSTOMERS_FAILURE";

export const GET_CUSTOMER_ID_SUCCESS = "GET_CUSTOMER_ID_SUCCESS";
export const GET_CUSTOMER_ID_FAILURE = "GET_CUSTOMER_ID_FAILURE";

export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_FAILURE = "CREATE_ACCOUNT_FAILURE";

export const GET_CART_ID_SUCCESS = "GET_CART_ID_SUCCESS";
export const GET_CART_ID_FAILURE = "GET_CART_ID_FAILURE";

